Models/Recipe.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Drawing;

namespace Recipease.Models;

public class Recipe
{
    private static readonly string[] value = { string.Empty };

    public int Id { get; set; }
    [Required]
    public string Title { get; set; } = string.Empty;

    public string Image {get; set; } = "https://static.wixstatic.com/media/bf242e_6133b4ae6a104cc2b50d70179f35efea~mv2.jpg/v1/fill/w_500,h_376,al_c,lg_1,q_80,enc_auto/food-placeholder.jpg";

    [Display(Name = "Date Added")]
    [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    [DataType(DataType.Date)]
    public DateTime DateAdded { get; set; }

    [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$")]
    
    public string? Cuisine { get; set; } = string.Empty;


    [DataType(DataType.Currency)]
    [Column(TypeName = "decimal(18, 2)")]
    public decimal Price { get; set; }

    public int Rating { get; set; }

    public string Summary { get; set; } = string.Empty;
    
    
}

Controllers/RecipesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.DotNet.Scaffolding.Shared.CodeModifier.CodeChange;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Recipease.Data;
using Recipease.Models;

namespace Recipease.Controllers
{
    public class RecipesController : Controller
    {
        private readonly RecipeaseContext _context;

        public RecipesController(RecipeaseContext context)
        {
            _context = context;
        }

        // GET: Recipes
        public async Task<IActionResult> Index(string searchString, string recipeCuisine)
        {
            if (_context.Recipe == null)
            {
                return Problem("Entity set 'Recipease.Recipe'  is null.");
            }

            IQueryable<string> cuisineQuery = from r in _context.Recipe
                                            orderby r.Cuisine
                                            select r.Cuisine;

            var recipes = from r in _context.Recipe
                         select r;

            if (!String.IsNullOrEmpty(searchString))
            {
                recipes = recipes.Where(s => s.Title!.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(recipeCuisine))
            {
                recipes = recipes.Where(x => x.Cuisine == recipeCuisine);
            }

            var recipeCuisineVM = new CuisineViewModel
            {
                Cuisines = new SelectList(await cuisineQuery.Distinct().ToListAsync()),
                Recipes = await recipes.ToListAsync()
            };

            return View(recipeCuisineVM);
        }

        [HttpPost]
        public string Index(string searchString, bool notUsed)
        {
            return "From [HttpPost]Index: filter on " + searchString;
        }

        // GET: Recipes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Recipe == null)
            {
                return NotFound();
            }

            var recipe = await _context.Recipe
                .FirstOrDefaultAsync(r => r.Id == id);
            if (recipe == null)
            {
                return NotFound();
            }

            return View(recipe);
        }

        // GET: Recipes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Recipes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Image,DateAdded,Cuisine,Price,Rating,Summary")] Recipe recipe)
        {
            if (ModelState.IsValid)
            {
                _context.Add(recipe);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(recipe);
        }

        // GET: Recipes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Recipe == null)
            {
                return NotFound();
            }
            

            var recipe = await _context.Recipe.FindAsync(id);
            if (recipe == null)
            {
                return NotFound();
            }
            return View(recipe);
        }

        public async Task<IActionResult> Rate(int? id)
        {


            var client = new HttpClient();
            var request = new HttpRequestMessage(HttpMethod.Get, "https://api.spoonacular.com/recipes/random?number=1&apiKey=fd93271a34a24f448d0d2c0973595b0b");
            var response = await client.SendAsync(request);
            response.EnsureSuccessStatusCode();

            var response_string = (await response.Content.ReadAsStringAsync());

            JObject jo = JObject.Parse(response_string);
            Recipe_New[] recipeArray = jo.SelectToken("recipes", false).ToObject<Recipe_New[]>();

            //List <Recipe_New> result_list = JsonConvert.DeserializeObject<List<Recipe_New>>(response_string);
            Recipe_New result = recipeArray[0];

            Recipe r = new Recipe();

            r.Title = result.Title;
                r.Image = result.Image;
                r.Rating = 0;
                r.Summary = result.Summary;
                r.Id = result.Id;
                r.Price = (decimal)result.PricePerServing;
                r.DateAdded = DateTime.Now;
     

            _context.Add(r);
            await _context.SaveChangesAsync();


            var rand = new Random();
            var total = _context.Recipe.Count();
            var rand_id = new int();

            do
            {
                rand_id = _context.Recipe.Skip(rand.Next(total)).First().Id;
            }
            while (rand_id == id);

            int new_id = result.Id;

            if (new_id == null || new_id == 0)
            {
                new_id = rand_id;
            }


            var recipe = await _context.Recipe
                .FirstOrDefaultAsync(r => r.Id == new_id);

            
            if (recipe == null)
            {
                return NotFound();
            }


            if (_context.Recipe == null)
            {
                return Problem("Entity set 'Recipease.Recipe'  is null.");
            }

      

            
            return View(recipe);
        }

        [HttpPost, ActionName("Good")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Good(int id)
        {


            if (_context.Recipe == null)
            {
                return Problem("Entity set 'RecipeaseContext.Recipe'  is null.");
            }
            var recipe = await _context.Recipe.FindAsync(id);
            if (recipe != null)
            {
                recipe.Rating = recipe.Rating + 1;
            }

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Rate));
            
            
        }
        [HttpPost, ActionName("Bad")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Bad(int id)
        {


            if (_context.Recipe == null)
            {
                return Problem("Entity set 'RecipeaseContext.Recipe'  is null.");
            }
            var recipe = await _context.Recipe.FindAsync(id);
            if (recipe != null)
            {
                recipe.Rating = recipe.Rating - 1;
            }

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Rate));


        }
        

        // POST: Recipes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,DateAdded,Cuisine,Price")] Recipe recipe)
        {
            if (id != recipe.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(recipe);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecipeExists(recipe.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(recipe);
        }

        // GET: Recipes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Recipe == null)
            {
                return NotFound();
            }

            var recipe = await _context.Recipe
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recipe == null)
            {
                return NotFound();
            }

            return View(recipe);
        }

        // POST: Recipes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Recipe == null)
            {
                return Problem("Entity set 'RecipeaseContext.Recipe'  is null.");
            }
            var recipe = await _context.Recipe.FindAsync(id);
            if (recipe != null)
            {
                _context.Recipe.Remove(recipe);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RecipeExists(int id)
        {
          return (_context.Recipe?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Recipes/Create.cshtml
@model Recipease.Models.Recipe

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Recipe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateAdded" class="control-label"></label>
                <input asp-for="DateAdded" class="form-control" />
                <span asp-validation-for="DateAdded" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cuisine" class="control-label"></label>
                <input asp-for="Cuisine" class="form-control" />
                <span asp-validation-for="Cuisine" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Summary" class="control-label"></label>
                <input asp-for="Summary" class="form-control" />
                <span asp-validation-for="Summary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Recipes/Delete.cshtml
@model Recipease.Models.Recipe

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Recipe</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class="col-sm-10">
            <img src="@Html.DisplayFor(model => model.Image)" alt="Image of Recipe" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAdded)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cuisine)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cuisine)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Summary)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Summary)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Recipes/Details.cshtml
@model Recipease.Models.Recipe

@{
    ViewData["Title"] = "Details";
    
}

<h1>Details</h1>

<div>
    <h4>Recipe</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class="col-sm-10">
            <img src="@Html.DisplayFor(model => model.Image)" alt="Image of Recipe"/>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAdded)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cuisine)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cuisine)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Summary)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Summary)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Recipes/Edit.cshtml
@model Recipease.Models.Recipe

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Recipe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateAdded" class="control-label"></label>
                <input asp-for="DateAdded" class="form-control" />
                <span asp-validation-for="DateAdded" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cuisine" class="control-label"></label>
                <input asp-for="Cuisine" class="form-control" />
                <span asp-validation-for="Cuisine" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Summary" class="control-label"></label>
                <input asp-for="Summary" class="form-control" />
                <span asp-validation-for="Summary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Recipes/Index.cshtml
@model Recipease.Models.CuisineViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<p>
    <a asp-action="Rate">Rating Mode (Tinder)</a>
</p>

<form asp-controller="Recipes" asp-action="Index" method="get">
    <p>
        <select asp-for="RecipeCuisine" asp-items="Model.Cuisines">
            <option value="">All</option>
        </select>

        Title: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Recipes![0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Recipes![0].DateAdded)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Recipes![0].Cuisine)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Recipes![0].Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Recipes![0].Rating)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Recipes!) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateAdded)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cuisine)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Recipes/Rate.cshtml
@model Recipease.Models.Recipe

@{
    ViewData["Title"] = "Rate";
}

<h1>Edit</h1>

<h4>Recipe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Image)
            </dt>
            <dd class="col-sm-10">
                <img src="@Html.DisplayFor(model => model.Image)" alt="Image of Recipe" />
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.DateAdded)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.DateAdded)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Cuisine)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Cuisine)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Rating)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Rating)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Price)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Price)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Summary)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Summary)
            </dd>
        </dl>
        <span style ="display: inline;">

            <form asp-action="Good">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Good" class="btn btn-primary" />
            </form>
            <form asp-action="Rate">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Skip" class="btn" />
            </form>
            <form asp-action="Bad">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Bad" class="btn btn-danger" />
            </form>
           
            
       </span>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}